services:

  odoo:
    image: odoo:${ODOO_VERSION}

    depends_on:
      - db

    ports:
      - "8069:8069"

    volumes:
      - ./addons:/mnt/extra-addons
      - ./docker/odoo/odoo.conf:/etc/odoo/odoo.conf
      - odoo_data:/var/lib/odoo


  db:
    image: postgres:16.2

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  odoo_data:
  postgres_data:
