services:

  odoo:
    image: odoo:17.0

    ports:
      - "8069:8069"

    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo

    depends_on:
      - db


  db:
    image: postgres:16.2

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  odoo_data:
  postgres_data:
