services:

  postgres:
    image: postgres:16
    container_name: odoo_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  odoo:
    image: odoo:17
    container_name: odoo_app
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_data:/var/lib/odoo

volumes:
  postgres_data:
  odoo_data: