"""Add sync_run and sync_logs

Revision ID: 275916f973dd
Revises: 0002_sync_entities
Create Date: 2026-07-24 11:46:46.976764
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '275916f973dd'
down_revision: Union[str, None] = '0002_sync_entities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=255), nullable=False),
    sa.Column('sync_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_records', sa.Integer(), nullable=False),
    sa.Column('stored_records', sa.Integer(), nullable=False),
    sa.Column('updated_records', sa.Integer(), nullable=False),
    sa.Column('error_records', sa.Integer(), nullable=False),
    sa.Column('sync_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_id'), 'sync_runs', ['id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.drop_constraint('contacts_odoo_id_key', 'contacts', type_='unique')
    op.drop_constraint('products_odoo_id_key', 'products', type_='unique')
    op.drop_constraint('sale_order_lines_odoo_id_key', 'sale_order_lines', type_='unique')
    op.drop_constraint('sale_orders_odoo_id_key', 'sale_orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sale_orders_odoo_id_key', 'sale_orders', ['odoo_id'])
    op.create_unique_constraint('sale_order_lines_odoo_id_key', 'sale_order_lines', ['odoo_id'])
    op.create_unique_constraint('products_odoo_id_key', 'products', ['odoo_id'])
    op.create_unique_constraint('contacts_odoo_id_key', 'contacts', ['odoo_id'])
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_sync_runs_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
