"""initial schema

Revision ID: 4d14337fb951
Revises: 
Create Date: 2026-07-23 22:45:58.652617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d14337fb951'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('odoo_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('odoo_id')
    )
    op.create_table('products',
    sa.Column('odoo_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('internal_reference', sa.String(length=64), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('product_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('odoo_id')
    )
    op.create_table('sale_orders',
    sa.Column('odoo_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.odoo_id'], ),
    sa.PrimaryKeyConstraint('odoo_id')
    )
    op.create_table('sale_order_lines',
    sa.Column('odoo_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sale_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.odoo_id'], ),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_orders.odoo_id'], ),
    sa.PrimaryKeyConstraint('odoo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_order_lines')
    op.drop_table('sale_orders')
    op.drop_table('products')
    op.drop_table('contacts')
    # ### end Alembic commands ###
