[options]
admin_passwd = $pbkdf2-sha512$600000$dA5hLKU0xjhHSMlZ6x3DmA$sdpTt9TK3uKSFvH.Nk0kCRkTd1d5.63O9FKETp7rtvCmiOHKM3f/PIJpLaO/Ix7ab5nNVqvO6OLs.S/syE5CiQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons

