"""initial_migration

Revision ID: 921f805734ac
Revises: 
Create Date: 2026-07-24 07:40:35.858361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921f805734ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_odoo_id'), 'contacts', ['odoo_id'], unique=True)
    op.create_table('products',
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('internal_reference', sa.String(length=100), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_odoo_id'), 'products', ['odoo_id'], unique=True)
    op.create_table('sync_runs',
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('received_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_table('sale_orders',
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], name=op.f('fk_sale_orders_customer_id_contacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_orders'))
    )
    op.create_index(op.f('ix_sale_orders_odoo_id'), 'sale_orders', ['odoo_id'], unique=True)
    op.create_table('sync_logs',
    sa.Column('sync_run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_odoo_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], name=op.f('fk_sync_logs_sync_run_id_sync_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_logs'))
    )
    op.create_table('sale_order_lines',
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('sale_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sale_order_lines_product_id_products')),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_orders.id'], name=op.f('fk_sale_order_lines_sale_order_id_sale_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_order_lines'))
    )
    op.create_index(op.f('ix_sale_order_lines_odoo_id'), 'sale_order_lines', ['odoo_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_order_lines_odoo_id'), table_name='sale_order_lines')
    op.drop_table('sale_order_lines')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_sale_orders_odoo_id'), table_name='sale_orders')
    op.drop_table('sale_orders')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_products_odoo_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_contacts_odoo_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
