"""add record_reference to sync_logs

Revision ID: 8cc0b20a19c1
Revises: fb0e0e728057
Create Date: 2026-07-23 23:06:02.742670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc0b20a19c1'
down_revision: Union[str, Sequence[str], None] = 'fb0e0e728057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_logs', sa.Column('record_reference', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'record_reference')
    # ### end Alembic commands ###
